import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { fromPdf, diffSnapshots } from '@pdf-testkit/core';

/**
 * Locks the general/pdfjs extraction path against REAL third-party output —
 * react-pdf, PDFKit, and Puppeteer/Chrome — not just FormePDF's own PDFs. The
 * committed fixtures are generated by packages/fixtures/producers/*.ts from each
 * library's documented pattern (representative invoice: title + section
 * headings + paragraph + a multi-column table that crosses a page break).
 *
 * These are the exact cases that surfaced two real extractor bugs — inter-column
 * whitespace collapsing table rows into one run, and small table text dragging
 * the heading-size baseline down so paragraphs mis-fired as headings — so they
 * guard against regressing either fix. Regenerate the fixtures with
 * `node packages/fixtures/producers/generate.ts`.
 */
function fixture(name: string): Uint8Array {
  const path = fileURLToPath(new URL(`../../fixtures/pdfs/${name}.pdf`, import.meta.url));
  return new Uint8Array(readFileSync(path));
}

const EXPECTED_HEADINGS = ['ACME Corporation', 'Bill To', 'Line Items'];
const PRODUCERS = ['react-pdf', 'pdfkit', 'puppeteer'] as const;

describe.each(PRODUCERS)('general path — %s output', (producer) => {
  it('detects exactly the real headings (no over- or under-firing)', async () => {
    const snap = await fromPdf(fixture(`${producer}-invoice`));
    const headings = snap.nodes.filter((n) => n.role === 'heading');
    // Exactly the three real headings — not bold body text or (Puppeteer) small
    // table cells dragging the baseline so paragraphs read as headings.
    expect(headings).toHaveLength(EXPECTED_HEADINGS.length);
    for (const expected of EXPECTED_HEADINGS) {
      expect(headings.some((h) => (h.text ?? '').includes(expected))).toBe(true);
    }
  });

  it('detects the table as a table (row/cell roles, not loose text)', async () => {
    const snap = await fromPdf(fixture(`${producer}-invoice`));
    expect(snap.nodes.some((n) => n.role === 'table')).toBe(true);
    expect(snap.nodes.filter((n) => n.role === 'cell').length).toBeGreaterThan(10);
  });

  it('POSITIVE: catches a demoted heading as a real regression', async () => {
    const base = await fromPdf(fixture(`${producer}-invoice`));
    const demoted = await fromPdf(fixture(`${producer}-invoice-demoted`));
    const result = diffSnapshots(base, demoted);
    expect(result.events.some((e) => e.type === 'heading-hierarchy-changed')).toBe(true);
  });

  it('NEGATIVE: reordering unrelated paragraphs produces no false regression', async () => {
    const base = await fromPdf(fixture(`${producer}-invoice`));
    const reordered = await fromPdf(fixture(`${producer}-invoice-reordered`));
    const result = diffSnapshots(base, reordered);
    const blocking = result.events.filter((e) => e.severity !== 'info');
    expect(blocking).toEqual([]);
  });
});
